# XenoMirror Lint Configuration
# Strict, agent-optimized rules for consistent code quality
# See agents.md for coding standards and patterns

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat warnings as errors (agents must fix immediately)
    missing_return: error
    dead_code: error
    unused_element: error
    unused_import: error

  exclude:
    - "**/*.g.dart"  # Generated code (Hive adapters)
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "android/unityLibrary/**"  # Unity export files

linter:
  rules:
    # Code Quality (Agent-enforceable)
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    avoid_print: true  # Use debugPrint or logger package

    # Safety (Prevent agent mistakes)
    always_declare_return_types: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_void: true
    no_logic_in_create_state: true

    # Flutter-specific (Prevent performance issues)
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true

    # Documentation (Help agents understand context)
    comment_references: true

    # Architecture enforcement
    always_use_package_imports: true
    avoid_relative_lib_imports: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
